# Generated by homebrew_formula.sh in yontrack/yontrack-cli, and pushed here by
# its release workflow. Anything edited by hand is lost at the next release;
# change the generator instead.
class Yontrack < Formula
  desc "Command line interface for Yontrack"
  homepage "https://github.com/yontrack/yontrack-cli"
  version "5.5.0"
  license "MIT"

  # The released binary rather than a build from source: see
  # docs/adr/0002-homebrew-ships-the-release-binary.md in yontrack/yontrack-cli.
  #
  # :nounzip stops Homebrew unpacking a bare executable, and leaves the staged
  # file named for its asset, which is what install picks up below.
  on_macos do
    on_arm do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.5.0/yontrack-darwin-arm64", using: :nounzip
      sha256 "6411ffb0d89a4db21b430a04b461f20131eaed2c0c4eafb13d27783244188f11"
    end
    on_intel do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.5.0/yontrack-darwin-amd64", using: :nounzip
      sha256 "08a5e21398c4eab908c9688a15dc605d92f66fa998d6ce45d66faa74b049858b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.5.0/yontrack-linux-arm64", using: :nounzip
      sha256 "e20bd3cfbd12d39d9e0947481f221a770bf9fa93e2e470a8135720d9832810a8"
    end
    on_intel do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.5.0/yontrack-linux-amd64", using: :nounzip
      sha256 "318379c76abca45258f24a89c6a524874019545ed7481b5e6e7dc607ade38018"
    end
  end

  def install
    # Exactly one asset is staged, under the name it carries in the release.
    bin.install Dir["yontrack-*"].first => "yontrack"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/yontrack version --cli").strip
  end
end
