# Generated by homebrew_formula.sh in yontrack/yontrack-cli, and pushed here by
# its release workflow. Anything edited by hand is lost at the next release;
# change the generator instead.
class Yontrack < Formula
  desc "Command line interface for Yontrack"
  homepage "https://github.com/yontrack/yontrack-cli"
  version "5.4.3"
  license "MIT"

  # The released binary rather than a build from source: see
  # docs/adr/0002-homebrew-ships-the-release-binary.md in yontrack/yontrack-cli.
  #
  # :nounzip stops Homebrew unpacking a bare executable, and leaves the staged
  # file named for its asset, which is what install picks up below.
  on_macos do
    on_arm do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.4.3/yontrack-darwin-arm64", using: :nounzip
      sha256 "15ab93b7da2b47b09b3074fc4fd5ed5f28c8a3e9e7a7c11eabe08397f6e67526"
    end
    on_intel do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.4.3/yontrack-darwin-amd64", using: :nounzip
      sha256 "02b38f45e76173b09ab0053f35e2d1ee05f392198c2324092e98bc46286230ee"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.4.3/yontrack-linux-arm64", using: :nounzip
      sha256 "c8ebd3bdc43339d0e9a0b9bb615b324b6e4522d1533200b2f57ca9ed9623cc14"
    end
    on_intel do
      url "https://github.com/yontrack/yontrack-cli/releases/download/5.4.3/yontrack-linux-amd64", using: :nounzip
      sha256 "b5038753696f0e88ec679281ad9513d27f288ecf742adc2812b9504752c06581"
    end
  end

  def install
    # Exactly one asset is staged, under the name it carries in the release.
    bin.install Dir["yontrack-*"].first => "yontrack"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/yontrack version --cli").strip
  end
end
